# Generated by Django 2.2.4 on 2019-10-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191023_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
