# Generated by Django 2.2.4 on 2019-10-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
        migrations.AddField(
            model_name='blog',
            name='commentcount',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
