# Generated by Django 2.2.4 on 2019-10-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='commentcount',
            field=models.IntegerField(),
        ),
    ]
